### ISSUE TITLE
Focus Node was used after being disposed

### ISSUE THREAD

**Issue by kaushiksundar** [prestigegodson/pin-entry-text-field#1]
I get the following error while using this package. This exception is thrown as soon as the UI is rendered on the screen

```
[ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
[        ] E/flutter (12978): A FocusNode was used after being disposed.
[        ] E/flutter (12978): Once you have called dispose() on a FocusNode, it can no longer be used.
[        ] E/flutter (12978): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:61:9)
[        ] E/flutter (12978): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:67:6)
[        ] E/flutter (12978): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:155:12)
[        ] E/flutter (12978): #3      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:103:5)
[        ] E/flutter (12978): #4      FocusManager._update (package:flutter/src/widgets/focus_manager.dart:449:20)
[        ] E/flutter (12978): #5      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] E/flutter (12978): #6      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by prestigegodson** [comment]
Hi kaushiksundar

i have pushed a bug fix to solve your issue, please let me know how it goes after upgrading the package to v0.1.3. 
Thanks

**Comment by kaushiksundar** [comment]
I am still facing that issue. I am looking at your code. I also have a few more suggestions. Let me know if you are planning to maintain this, else I can make a new package.

**Comment by prestigegodson** [comment]
@ Added you as a collaborator, anticipating your fix.
Thanks

**Comment by prestigegodson** [comment]
@kaushiksundar  added you as a collaborator, anticipating your fix.

Thanks
